// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt-4YN5A0X-uLjgkXh6T6qWhos2NSHrCY',
    appId: '1:393308389712:web:084a15385b3cba15adec55',
    messagingSenderId: '393308389712',
    projectId: 'grocerybynadeem',
    authDomain: 'grocerybynadeem.firebaseapp.com',
    storageBucket: 'grocerybynadeem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWS5T2tg_tEgiVnllsRn-8uQLPx1F-kH8',
    appId: '1:393308389712:android:5021ab7576266f45adec55',
    messagingSenderId: '393308389712',
    projectId: 'grocerybynadeem',
    storageBucket: 'grocerybynadeem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ1UGPQIiOw3CJHU0douxiQYuBr07TGyk',
    appId: '1:393308389712:ios:4746b46c22501a51adec55',
    messagingSenderId: '393308389712',
    projectId: 'grocerybynadeem',
    storageBucket: 'grocerybynadeem.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ1UGPQIiOw3CJHU0douxiQYuBr07TGyk',
    appId: '1:393308389712:ios:4746b46c22501a51adec55',
    messagingSenderId: '393308389712',
    projectId: 'grocerybynadeem',
    storageBucket: 'grocerybynadeem.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt-4YN5A0X-uLjgkXh6T6qWhos2NSHrCY',
    appId: '1:393308389712:web:d7978b2b327ca8f2adec55',
    messagingSenderId: '393308389712',
    projectId: 'grocerybynadeem',
    authDomain: 'grocerybynadeem.firebaseapp.com',
    storageBucket: 'grocerybynadeem.firebasestorage.app',
  );
}
